config/routes.rb
HomePhone::Application.routes.draw do
  resources :whos_home_responses

  resources :whos_home_requests

  resources :registrations

  resources :residencies

  resources :houses

  resources :users
  
  post 'houses/:id/add_users/' => 'houses#add_users'
	get 'users/find/:phone_number/' => 'users#find_user'
	get 'users/:id/whos_home/:house_id' => 'users#whos_home'
	post 'users/register' => 'users#register'

end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: [:show, :edit, :update, :destroy]

  # GET /houses
  # GET /houses.json
  def index
    @houses = House.all
  end

  # GET /houses/1
  # GET /houses/1.json
  def show
  end

  # GET /houses/new
  def new
    @house = House.new
  end

  # GET /houses/1/edit
  def edit
  end

  # POST /houses
  # POST /houses.json
  def create
    @house = House.new(house_params)

    respond_to do |format|
      if @house.save
        format.html { redirect_to @house, notice: 'House was successfully created.' }
        format.json { render action: 'show', status: :created, location: @house }
      else
        format.html { render action: 'new' }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /houses/1
  # PATCH/PUT /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html { redirect_to @house, notice: 'House was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1
  # DELETE /houses/1.json
  def destroy
    @house.destroy
    respond_to do |format|
      format.html { redirect_to houses_url }
      format.json { head :no_content }
    end
  end
  
  def add_users
		logger.debug "in add_users"
    @house = House.find(params[:id])    
    usersHash = ActiveSupport::JSON.decode(request.raw_post)
    usersArray = usersHash["users"]
    justIDsArray = usersArray.map { |user| user["id"] }
		logger.debug "id array"
		logger.debug justIDsArray.inspect
    users = User.find(justIDsArray)
    logger.debug users.inspect
    
    users.each do |user|
      add_user user
    end
    
    respond_to do |format|
      
        format.html { redirect_to @house, notice: 'House was successfully updated.' }
        format.json { head :no_content }

    end
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house
      @house = House.find(params[:id])
    end
    
    def add_user(user)
      
      residency = Residency.new
      residency.user = user
      residency.house = @house
      if residency.save
				logger.debug "saved"
			else
				logger.debug "not saved"
			end
    end
      
      

    # Never trust parameters from the scary internet, only allow the white list through.
    def house_params
      params.require(:house).permit(:house_name, :longitude, :latitude, :address, :phone_number)
    end
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/houses/_form.html.erb
<%= form_for(@house) do |f| %>
  <% if @house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
      <% @house.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :house_name %><br>
    <%= f.text_field :house_name %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/houses/edit.html.erb
<h1>Editing house</h1>

<%= render 'form' %>

<%= link_to 'Show', @house %> |
<%= link_to 'Back', houses_path %>

app/views/houses/index.html.erb
<h1>Listing houses</h1>

<table>
  <thead>
    <tr>
      <th>House name</th>
      <th>Longitude</th>
      <th>Latitude</th>
      <th>Address</th>
      <th>Phone number</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @houses.each do |house| %>
      <tr>
        <td><%= house.house_name %></td>
        <td><%= house.longitude %></td>
        <td><%= house.latitude %></td>
        <td><%= house.address %></td>
        <td><%= house.phone_number %></td>
        <td><%= link_to 'Show', house %></td>
        <td><%= link_to 'Edit', edit_house_path(house) %></td>
        <td><%= link_to 'Destroy', house, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New House', new_house_path %>

app/views/houses/new.html.erb
<h1>New house</h1>

<%= render 'form' %>

<%= link_to 'Back', houses_path %>

app/views/houses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>House name:</strong>
  <%= @house.house_name %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @house.longitude %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @house.latitude %>
</p>

<p>
  <strong>Address:</strong>
  <%= @house.address %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @house.phone_number %>
</p>

<%= link_to 'Edit', edit_house_path(@house) %> |
<%= link_to 'Back', houses_path %>