config/routes.rb
HomePhone::Application.routes.draw do
  resources :whos_home_responses

  resources :whos_home_requests

  resources :registrations

  resources :residencies

  resources :houses

  resources :users
  
  post 'houses/:id/add_users/' => 'houses#add_users'
	get 'users/find/:phone_number/' => 'users#find_user'
	get 'users/:id/whos_home/:house_id' => 'users#whos_home'
	post 'users/register' => 'users#register'

end

app/models/residency.rb
class Residency < ActiveRecord::Base
  
  belongs_to :house
  belongs_to :user
end

app/controllers/residencies_controller.rb
class ResidenciesController < ApplicationController
  before_action :set_residency, only: [:show, :edit, :update, :destroy]

  # GET /residencies
  # GET /residencies.json
  def index
    @residencies = Residency.all
  end

  # GET /residencies/1
  # GET /residencies/1.json
  def show
  end

  # GET /residencies/new
  def new
    @residency = Residency.new
  end

  # GET /residencies/1/edit
  def edit
  end

  # POST /residencies
  # POST /residencies.json
  def create
    @residency = Residency.new(residency_params)

    respond_to do |format|
      if @residency.save
        format.html { redirect_to @residency, notice: 'Residency was successfully created.' }
        format.json { render action: 'show', status: :created, location: @residency }
      else
        format.html { render action: 'new' }
        format.json { render json: @residency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /residencies/1
  # PATCH/PUT /residencies/1.json
  def update
    respond_to do |format|
      if @residency.update(residency_params)
        format.html { redirect_to @residency, notice: 'Residency was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @residency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /residencies/1
  # DELETE /residencies/1.json
  def destroy
    @residency.destroy
    respond_to do |format|
      format.html { redirect_to residencies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_residency
      @residency = Residency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def residency_params
      params.require(:residency).permit(:user_id, :house_id)
    end
end

app/helpers/residencies_helper.rb
module ResidenciesHelper
end

app/views/residencies/_form.html.erb
<%= form_for(@residency) do |f| %>
  <% if @residency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@residency.errors.count, "error") %> prohibited this residency from being saved:</h2>

      <ul>
      <% @residency.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :house_id %><br>
    <%= f.text_field :house_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/residencies/edit.html.erb
<h1>Editing residency</h1>

<%= render 'form' %>

<%= link_to 'Show', @residency %> |
<%= link_to 'Back', residencies_path %>

app/views/residencies/index.html.erb
<h1>Listing residencies</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>House</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @residencies.each do |residency| %>
      <tr>
        <td><%= residency.user_id %></td>
        <td><%= residency.house_id %></td>
        <td><%= link_to 'Show', residency %></td>
        <td><%= link_to 'Edit', edit_residency_path(residency) %></td>
        <td><%= link_to 'Destroy', residency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Residency', new_residency_path %>

app/views/residencies/new.html.erb
<h1>New residency</h1>

<%= render 'form' %>

<%= link_to 'Back', residencies_path %>

app/views/residencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @residency.user_id %>
</p>

<p>
  <strong>House:</strong>
  <%= @residency.house_id %>
</p>

<%= link_to 'Edit', edit_residency_path(@residency) %> |
<%= link_to 'Back', residencies_path %>