config/routes.rb
HomePhone::Application.routes.draw do
  resources :whos_home_responses

  resources :whos_home_requests

  resources :registrations

  resources :residencies

  resources :houses

  resources :users
  
  post 'houses/:id/add_users/' => 'houses#add_users'
	get 'users/find/:phone_number/' => 'users#find_user'
	get 'users/:id/whos_home/:house_id' => 'users#whos_home'
	post 'users/register' => 'users#register'

end

app/models/whos_home_request.rb
class WhosHomeRequest < ActiveRecord::Base
	belongs_to :user
	has_many :whos_home_responses

	attr_accessor :num_recipients
end

app/controllers/whos_home_requests_controller.rb
class WhosHomeRequestsController < ApplicationController
  before_action :set_whos_home_request, only: [:show, :edit, :update, :destroy]

  # GET /whos_home_requests
  # GET /whos_home_requests.json
  def index
    @whos_home_requests = WhosHomeRequest.all
  end

  # GET /whos_home_requests/1
  # GET /whos_home_requests/1.json
  def show
  end

  # GET /whos_home_requests/new
  def new
    @whos_home_request = WhosHomeRequest.new
  end

  # GET /whos_home_requests/1/edit
  def edit
  end

  # POST /whos_home_requests
  # POST /whos_home_requests.json
  def create
    @whos_home_request = WhosHomeRequest.new(whos_home_request_params)

    respond_to do |format|
      if @whos_home_request.save
        format.html { redirect_to @whos_home_request, notice: 'Whos home request was successfully created.' }
        format.json { render action: 'show', status: :created, location: @whos_home_request }
      else
        format.html { render action: 'new' }
        format.json { render json: @whos_home_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /whos_home_requests/1
  # PATCH/PUT /whos_home_requests/1.json
  def update
    respond_to do |format|
      if @whos_home_request.update(whos_home_request_params)
        format.html { redirect_to @whos_home_request, notice: 'Whos home request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @whos_home_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /whos_home_requests/1
  # DELETE /whos_home_requests/1.json
  def destroy
    @whos_home_request.destroy
    respond_to do |format|
      format.html { redirect_to whos_home_requests_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_whos_home_request
      @whos_home_request = WhosHomeRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def whos_home_request_params
      params.require(:whos_home_request).permit(:user_id, :num_recipients)
    end
end

app/helpers/whos_home_requests_helper.rb
module WhosHomeRequestsHelper
end

app/views/whos_home_requests/_form.html.erb
<%= form_for(@whos_home_request) do |f| %>
  <% if @whos_home_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@whos_home_request.errors.count, "error") %> prohibited this whos_home_request from being saved:</h2>

      <ul>
      <% @whos_home_request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :num_recipients %><br>
    <%= f.number_field :num_recipients %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/whos_home_requests/edit.html.erb
<h1>Editing whos_home_request</h1>

<%= render 'form' %>

<%= link_to 'Show', @whos_home_request %> |
<%= link_to 'Back', whos_home_requests_path %>

app/views/whos_home_requests/index.html.erb
<h1>Listing whos_home_requests</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Num recipients</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @whos_home_requests.each do |whos_home_request| %>
      <tr>
        <td><%= whos_home_request.user_id %></td>
        <td><%= whos_home_request.num_recipients %></td>
        <td><%= link_to 'Show', whos_home_request %></td>
        <td><%= link_to 'Edit', edit_whos_home_request_path(whos_home_request) %></td>
        <td><%= link_to 'Destroy', whos_home_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Whos home request', new_whos_home_request_path %>

app/views/whos_home_requests/new.html.erb
<h1>New whos_home_request</h1>

<%= render 'form' %>

<%= link_to 'Back', whos_home_requests_path %>

app/views/whos_home_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @whos_home_request.user_id %>
</p>

<p>
  <strong>Num recipients:</strong>
  <%= @whos_home_request.num_recipients %>
</p>

<%= link_to 'Edit', edit_whos_home_request_path(@whos_home_request) %> |
<%= link_to 'Back', whos_home_requests_path %>